Philosophy 244: Bisimulations and the Standard Translation +
[smallcaps]#Guest Lecture: Cosmo Grant, October 26, 2016# +

== The Plan

We’ll look at some more metatheory of propositional modal logic. Our
previous work on propositional modal logic focused on _frames_. Today
we’ll focus on _models_. The central new concept is that of a
_bisimulation_ between two models. We’ll use bisimulations to prove some
results about the _expressive power_ of modal logic. And bisimulations
turn out to be exactly what we need to connect modal logic with
first-order logic. Here’s the plan:

. Bisimulations: definition and examples
. Bisimulations and modal equivalence
. Bisimulations and expressive power
. Bisimulations and the Standard Translation

== Bisimulations: definition and examples

Let’s say that latexmath:[(M,w)], latexmath:[(M',w')] are _modally
equivalent_ just if for every formula latexmath:[\phi],
latexmath:[(M,w) \models \phi] iff latexmath:[(M',w') \models \phi].

When are latexmath:[(M,w)], latexmath:[(M',w')] modally equivalent?
Well, if there is an _isomorphism_ latexmath:[f : W \rightarrow W'] then
latexmath:[(M,w)], latexmath:[(M',w')] will certainly be modally
equivalent. But an isomorphism is over-kill: it guarantees modal
equivalence but in a heavy-handed way. Can we do better?

Let latexmath:[M = (W,R,V)], latexmath:[M' = (W',R',V')] be models. A
non-empty binary relation latexmath:[Z \subseteq W \times W'] is a
_bisimulation between latexmath:[M] and latexmath:[M']_ just if the
following conditions are satisfied:

. _Atomic harmony:_ If latexmath:[wZw'] then latexmath:[w] and
latexmath:[w'] satisfy the same proposition letters.
. _Forth condition:_ If latexmath:[wZw'] and latexmath:[Rwv] then there
exists latexmath:[v'] such that latexmath:[R'w'v'] and latexmath:[vZv'].
. _Back condition:_ If latexmath:[wZw'] and latexmath:[R'w'v'] then
there exists latexmath:[v] such that latexmath:[vZv'] and
latexmath:[Rwv].

If there is a bisimulation between latexmath:[(M,w)] and
latexmath:[(M',w')], we’ll write
latexmath:[(M,w) \leftrightarroweq (M',w')], and say that latexmath:[w],
latexmath:[w'] are _bisimilar_.

== Bisimulations and modal equivalence

If latexmath:[(M,w) \leftrightarroweq (M',w')] then
latexmath:[(M,w) \leftrightsquigarrow (M',w')].

_Proof._ We need to show that for all formulas latexmath:[\phi] and
models latexmath:[(M,w), (M',w')], if
latexmath:[(M,w) \leftrightarroweq (M',w')] then
latexmath:[(M,w) \models \phi] iff latexmath:[(M',w') \models \phi]. We
proceed by strong induction on complexity. Fix a formula
latexmath:[\phi].

_Induction Hypothesis:_ For every shorter formula latexmath:[\psi] and
all models latexmath:[(M,w)], latexmath:[(M',w')], if
latexmath:[(M,w) \leftrightarroweq (M',w')] then
latexmath:[(M,w) \models \psi] iff latexmath:[(M',w') \models \psi].

_Case 1:_ latexmath:[\phi] is atomic. The result follows from atomic
harmony.

_Case 2:_ latexmath:[\phi] is a Boolean combination of shorter formulas.
The result is by IH and the satisfaction definitions.

_Case 3:_ latexmath:[\phi] is latexmath:[\diamond \psi]. Suppose
latexmath:[(M,w) \leftrightarroweq (M',w')] and
latexmath:[(M,w) \models \diamond \psi]. So there exists latexmath:[v]
in latexmath:[M] such that latexmath:[Rwv] and
latexmath:[(M,v) \models \psi]. Since
latexmath:[(M,w) \leftrightarroweq (M',w')], the forth condition tells
us that there exists latexmath:[v'] in latexmath:[M'] such that
latexmath:[R'w'v'] and latexmath:[(M,v) \leftrightarroweq (M',v')]. By
IH, latexmath:[(M',v') \models \psi]. So
latexmath:[(M',w') \models \diamond \psi]. The converse is similar. ◻

Are worlds which satisfy the same modal formulas always bisimilar? After
all, bisimilarity seems to perfectly reflect the satisfaction
definitions. Perhaps we can use the modal formulas to construct a
bisimulation between modally equivalent worlds. Not so!

Take a world latexmath:[w]. For each latexmath:[n], add an
latexmath:[R]-branch of length latexmath:[n] coming out of
latexmath:[w]. That’s latexmath:[M]. Now take a world latexmath:[w'].
For each latexmath:[n], add an latexmath:[R']-branch of length
latexmath:[n] coming out of latexmath:[w'], as before. But _also_ add an
infinite latexmath:[R']-branch coming out of latexmath:[w']. That’s
latexmath:[M']. Now, latexmath:[(M,w) \leftrightsquigarrow (M',w')].
(Why?) But there is no bisimulation between latexmath:[(M,w)] and
latexmath:[(M',w')]. (Why not?)

We _can_, however, get a restricted converse to Proposition 1. A
preliminary definition: a model latexmath:[M] is _image-finite_ if each
world in latexmath:[M] can see only finitely many worlds.

Let latexmath:[M], latexmath:[M'] be image-finite models. For all
latexmath:[w \in W], latexmath:[w' \in W'], if
latexmath:[(M,w) \leftrightsquigarrow (M',w')] then
latexmath:[(M,w) \leftrightarroweq (M',w')].

_Proof._ We will show that the relation of modal equivalence is itself a
bisimulation. That is, define
latexmath:[Z := \{ (w,w') \in W \times W' : (M,w) \leftrightsquigarrow (M',w') \}].
We need to check that latexmath:[Z] satisfies our three conditions.

Atomic harmony is immediate. Suppose for contradiction that
latexmath:[Rwv] and latexmath:[wZw'] but there is no latexmath:[v'] in
latexmath:[M'] such that latexmath:[Rw'v'] and latexmath:[vZv']. Let
latexmath:[S'] be the set of successors of latexmath:[w']. Note that
latexmath:[S'] must be non-empty (why?) and finite, say
latexmath:[S' = \{w'_1, w'_2, w'_3, \ldots \}]. By assumption, for each
latexmath:[w'_i \in S'], there exists a formula latexmath:[\psi_i] such
that latexmath:[(M,v) \models \psi] but
latexmath:[(M',w'_i) \not\models \psi]. Hence:

latexmath:[(M,w) \models \diamond (\psi_1 \wedge \psi_2 \wedge \ldots \wedge \psi_n)]
but
latexmath:[(M',w') \not\models \diamond (\psi_1 \wedge \psi_2 \wedge \ldots \wedge \psi_n).]

Contradiction. That verifies the forth condition. Checking the back
condition is similar. ◻

== Bisimulations and expressive power

What properties of models can we talk about within the modal language?
First, we need to make talk about '`talking about`' precise.

Let latexmath:[P] be a property of (pointed) models. Let’s say that a
formula latexmath:[\phi] _defines_ latexmath:[P] just if, for any model
latexmath:[(M,w)], we have latexmath:[(M,w) \models \phi] just if
latexmath:[(M,w)] has property latexmath:[P]. A property latexmath:[P]
is _definable_ if there is some formula which defines it.

Bisimulations give us a general strategy for showing that a property is
not definable: find bisimilar models such that one has the property and
the other doesn’t.

For example, let’s say that latexmath:[(M,w)] is _reflexive_ just if
latexmath:[Rww]. Is reflexivity definable (over pointed models)? No! Can
you find suitable models?

From a negative point of view, such results tell us about the limits on
what the modal language can say. From a positive point of view, they
suggest ways of transforming models without affecting satisfiability—a
handy tool.

== Bisimulations and the Standard Translation

The modal language is interpreted over _graph-like structures_. We can
_also_ interpret a first-order language latexmath:[\mathcal{L}] over
such structures. That’s interesting, because then we can compare
first-order logic and modal logic.

What is latexmath:[\mathcal{L}]? The non-logical symbols of
latexmath:[\mathcal{L}] are the unary predicates latexmath:[P_0],
latexmath:[P_1], latexmath:[\ldots], corresponding to the proposition
letters latexmath:[p_0], latexmath:[p_1], latexmath:[\ldots], and a
binary relation symbol latexmath:[R].

We interpret latexmath:[\mathcal{L}] using an ordinary modal model—no
adjustment needed!

We define the _standard translation latexmath:[ST_x]_ taking modal
formulas to first order formulas with one free variable latexmath:[x],
as follows:

. latexmath:[ST_x(p) = Px]
. latexmath:[ST_x(\neg \phi) = \neg ST_x(\phi)]
. latexmath:[ST_x(\phi \vee \psi) = ST_x(\phi) \vee ST_x(\psi)]
. latexmath:[ST_x(\diamond \phi) = \exists y (Rxy \wedge ST_y(\phi))],
where latexmath:[y] is a fresh variable

Here is the fundamental fact:

For all latexmath:[\mathcal{M}] and all states latexmath:[w] of
latexmath:[M]:
latexmath:[(M,w) \models \phi \text{ iff } M \models ST_x(\phi)[w]].

The theorem provides "`a bridge between modal and first-order logic—and
we can use this bridge to import results, ideas and proof techniques
from one to the other.`"

Which first-order formulas are translations of modal formulas (up to
logical equivalence)? That question is answered by van Benthem’s
Theorem. We need a preliminary definition:

A first-order formula latexmath:[\alpha(x)] in latexmath:[\mathcal{L}]
is _invariant for bisimulations_ if for all models latexmath:[M],
latexmath:[N] and all states latexmath:[w \in M], latexmath:[v \in N],
and all bisimulations latexmath:[Z] between latexmath:[M] and
latexmath:[N] such that latexmath:[wZv], we have
latexmath:[M \models \alpha(x)[w]] iff
latexmath:[N \models \alpha(x)[v]].

Let latexmath:[\alpha(x)] be a first order formula in
latexmath:[\mathcal{L}]. Then latexmath:[\alpha(x)] is equivalent to the
standard translation of a modal formula just if it’s invariant for
bisimulations.
